server:
  port: 8001

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  redis:
    jedis:
      pool:
        max-wait: 1000ms
        max-active: 600
        max-idle: 300
    host: 127.0.0.1
    port: 6379
    password:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /



biz:
  interceptor:
    access: true
    checkToken: true
#  oss:
#    endpoint: "localhost"
#    region: "1"
#    pathStyleAccess: true
#    accessKey: "1"
#    secretKey: "1"
#    maxConnections: 10
  cache:
    redis-cache: true
  log:
    enable: true
  rabbitmq:
    enable: false





