server:
  port: 8001

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  redis:
    jedis:
      pool:
        max-wait: 1000ms
        max-active: 600
        max-idle: 300
    host: 127.0.0.1
    port: 6379
    password:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

logging:
  level:
    root: info
  pattern:
    # 控制台输出
    console: "%clr([%X{traceId}]){faint} %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){faint} %highlight(%-5level) %clr(%logger{36}){cyan} : %msg%n"
    # 文件输出
    file: "[%X{traceId}] %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

biz:
  trace:
    enabled: false





